/* istanbul ignore file */

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED_USERNAME_ALREADY_TAKEN =
  "REGISTER_FAILED_USERNAME_ALREADY_TAKEN";
export const REGISTER_FAILED_EMAIL_ALREADY_TAKEN =
  "REGISTER_FAILED_EMAIL_ALREADY_TAKEN";
export const REGISTER_FAILED_EMAIL_ALREADY_AUTHENTICATED =
  "REGISTER_FAILED_EMAIL_ALREADY_AUTHENTICATED";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const PROFILE_ACCESS = "PROFILE_ACCESS";
