version: '3.8'

services:
  nginx:
    container_name: frontend
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        REACT_APP_IS_IN_DOCKER_COMPOSE_MODE: 1
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      app_network:
    env_file:
      - .env
    volumes:
      - staticfiles:/staticfiles

  backend:
    container_name: backend
    ports:
      - "8000:8000"
    build:
      context: backend
      dockerfile: ./Dockerfile
    links:
      - database
    depends_on:
      - database
    networks:
      - app_network
    env_file:
      - .env
    volumes:
      - staticfiles:/app/staticfiles/
    
  database:
    container_name: database
    image: postgres:latest
    command: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data
    networks:
      - app_network
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d","db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  postgres_data:
  staticfiles:
  static:

networks:
  app_network:
    name: Application network