version: '3.8'

services:
  nginx:
    container_name: app_server_conf
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - PUBLIC_URL=127.0.0.1
    networks:
      app_network:
    env_file:
      - .env
    volumes:
      - staticfiles:/staticfiles

  backend:
    container_name: backend
    ports:
      - "8000:8000"
    build:
      context: backend
      dockerfile: ./Dockerfile
    links:
      - database
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - app_network
    volumes:
      - staticfiles:/app/staticfiles/
    
  database:
    container_name: database
    image: postgres:latest
    build:
      context: ./postgres/
      dockerfile: ./Dockerfile
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=backend_db
      - POSTGRES_USER=backend_website
      - POSTGRES_PASSWORD=Quen7tin.
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d","db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  postgres_data:
  staticfiles:
  static:

networks:
  app_network:
    name: Application network