# Generated by Django 4.1.7 on 2023-05-26 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='User email')),
                ('username', models.TextField(unique=True, verbose_name='Username')),
                ('is_active', models.BooleanField(default=True)),
                ('is_currently_logged_in', models.BooleanField(default=False, verbose_name='Is logged in?')),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('registration_date', models.DateField(default=datetime.date.today, verbose_name='Registration date')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
