# Generated by Django 4.1.7 on 2023-05-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_image',
            field=models.FileField(blank=True, null=True, upload_to='user', verbose_name='User profile picture'),
        ),
    ]
