# Generated by Django 4.1.7 on 2023-05-30 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0002_user_avatar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Registration date'),
        ),
    ]
