# Generated by Django 4.1.7 on 2023-06-09 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0004_alter_user_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registration date'),
        ),
    ]
