# Generated by Django 4.1.7 on 2023-07-06 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0006_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='user_id',
            new_name='user',
        ),
    ]
