name: Backend service unit tests & linting

on: push

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build web app stack
        run: docker-compose up -d --build
      - name: Check if the code is written badly or not
        run: docker exec backend make lint
      - name: Generate unit test coverage report of user created code while launching the unit test suite.
        run: docker exec backend make coverage_gen
      - name: Displays result
        run: docker exec backend make coverage_shell